### ISSUE TITLE
 Cannot find module '[...]/node_modules/@yoichiro/vite-plugin-handlebars/dist/internal'

### ISSUE THREAD

**Issue by denniseffing** [yoichiro/vite-plugin-handlebars#8] opened 2024-09-11 15:15 UTC
Hi,

I found this plugin via [vitejs/awesome-vite](https://github.com/vitejs/awesome-vite?tab=readme-ov-file#plugins) because frankly, all other handlebars plugins I've found and tried so far are quite lacking. 😞 

However, installing this plugin and then running `npm run dev` leads to the following error:

```
failed to load config from [...]/handlebars-test/vite.config.ts
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '[...]/handlebars-test/node_modules/@yoichiro/vite-plugin-handlebars/dist/internal' imported from [...]/handlebars-test/node_modules/@yoichiro/vite-plugin-handlebars/dist/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:260:11)
    at moduleResolve (node:internal/modules/esm/resolve:920:10)
    at defaultResolve (node:internal/modules/esm/resolve:1119:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:511:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:126:49)
```

> ℹ️ I omitted the filepaths on my filesystem using the `[...]` notation.

Steps to reproduce:
1. Run `npm create vite@latest`
2. Choose `Vanilla` framework & language `TypeScript`
3. Run `npm install && npm install --save-dev @yoichiro/vite-plugin-handlebars`
4. Create a `vite.config.ts` with the following contents:

```typescript
import {defineConfig} from 'vite';
import handlebarsPlugin from '@yoichiro/vite-plugin-handlebars';

export default defineConfig({
  plugins: [
    handlebarsPlugin()
  ]
})
```

5. Run `npm run dev`

**Comment by yoichiro** [comment] 2024-09-14 10:20
@denniseffing Thank you for reporting this issue. However, when trying the steps you teached me, `npm run dev` worked normally. If you wrote your `vite.config.ts` or `vite.config.js` file, could you show me the file?

**Comment by denniseffing** [comment] 2024-09-14 10:25
Whoops, sorry, I forgot a step:

5. Create a `vite.config.ts` with the following contents:

```typescript
import {defineConfig} from 'vite';
import handlebarsPlugin from '@yoichiro/vite-plugin-handlebars';

export default defineConfig({
  plugins: [
    handlebarsPlugin()
  ]
})
```

I added the step to the initial comment as well.

**Comment by yoichiro** [comment] 2024-09-14 10:28
@denniseffing Thank you for reporting the `vite.config.ts` file. I can reproduce this issue on my PC. I intend to investigate the cause of this issue within a few days.

**Comment by yoichiro** [comment] 2024-09-14 12:42
@denniseffing I have released the new version 1.1.3 to fix this issue, and I have confirmed that this issue was fixed using the version on my PC. Could you use the 1.1.3 to confirm whether this issue is fixed or not on your environment? If the plugin works on your environment, I will close this issue.

**Comment by denniseffing** [comment] 2024-09-14 13:05
The import works now, thank you!

**Comment by yoichiro** [comment] 2024-09-14 21:42
@denniseffing Thank you for your contribution!

**Closed by yoichiro** 2024-09-14 21:42 UTC
Labels: bug
